print("Hello, world!")
print("hi, there")
print("another print")
print("one more")
print("line")
print("ok")
print("here")
print("ok")
print("commit")
print("commit")
print("here")
print("kk")
print("kk")
print("kk2")
print("kk3")
print("kk4")
print("kk5")
print("kk6")
print("kk7")
print("kk8")
print("kk9")
print("kk10")
print("kk10")
print("kk10")
print("kk10")
print("kk10")
print("kk10")
print("kk10")